{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.forgejo-runner;

  # Defaults match what we agreed on in the platform-doc for the Odroid host.
  defaultUrl    = "https://forgejo.tail5bbc4.ts.net";
  defaultLabels = [ "self-hosted" "linux" "x86_64" ];

  # Flow-style YAML list: [a, b, c]. Avoids indentation issues that
  # block-style lists introduce when generated from Nix `''` strings.
  yamlList = items: "[${concatStringsSep ", " items}]";

  # The generated config.yaml. The token never enters the Nix store:
  # forgejo-runner reads it at startup via `token_url: file:`.
  # The UUID is the only identifier baked in. UUIDs are not credentials,
  # so it's acceptable for them to live in /nix/store.
  configFile = pkgs.writeText "forgejo-runner-config.yaml" (''
    # Generated by modules/forgejo-runner.nix — do not edit by hand.
    # Regenerated on every `nixos-rebuild switch`.

    log:
      level: info

    runner:
      file:           /var/lib/forge-runner/.runner
      capacity:       ${toString cfg.capacity}
      timeout:        ${cfg.jobTimeout}
      insecure:       false
      fetch_timeout:  ${cfg.fetchTimeout}
      labels:         ${yamlList cfg.labels}

    cache:
      # Cache is disabled for v1. Re-enable with a real cache host
      # when we actually need caching.
      enabled: false

    container:
      # Rootless Docker is already enabled on the host. The runner
      # spawns one ephemeral container per job as UID `forge` (1000)
      # with --userns=keep-id so bind mounts map back to forge-runner.
      network:        ""
      privileged:     false
      force_pull:     false
      runtime:        ""
      workdir_parent: ${cfg.containerWorkdirParent}
      options:        >-
        --userns=keep-id

    host:
      workdir_parent: ${cfg.hostWorkdirParent}

    # v12+ requires server connections to be declared in config.
    # The UUID is baked here; the token is read from a file at
    # runtime via `token_url: file:`.
    server:
      connections:
        ${cfg.connectionName}:
          url:       ${cfg.url}
          uuid:      ${cfg.uuid}
          token_url: file:${cfg.tokenFile}
          labels:    ${yamlList cfg.labels}
  '' + cfg.extraConfig);
in
{
  options.services.forgejo-runner = {
    enable = mkEnableOption "Forgejo Actions runner daemon";

    name = mkOption {
      type = types.str;
      default = "odroid-runner";
      description = ''
        Display name for the runner. Logged in Actions runs; shown on
        the Runners page.
      '';
    };

    connectionName = mkOption {
      type = types.str;
      default = "ewt-lab";
      description = ''
        Key under `server.connections:` in the config. One per Forgejo
        instance the runner connects to. Default 'ewt-lab' matches the
        primary org.
      '';
    };

    url = mkOption {
      type = types.str;
      default = defaultUrl;
      description = "Forgejo instance URL.";
    };

    uuid = mkOption {
      type = types.str;
      example = "5e3d8c2a-1f7b-4d9e-a8c6-3f2e1d0c9b8a";
      description = ''
        The runner's UUID. Shown ONCE by the Forgejo web UI when you
        create a new runner. Not a credential — safe to bake into the
        generated config.yaml (which lives in /nix/store).
      '';
    };

    tokenFile = mkOption {
      type = types.path;
      default = "/etc/nixos/secrets/forgejo-runner-token";
      description = ''
        Path to a file containing the runner's token (one line, the
        opaque token string). The token is shown ONCE by the Forgejo
        web UI when you create a new runner. The file MUST be mode
        600 or 400, owned by root or forge-runner. The file is read
        by forgejo-runner at startup via `token_url: file:<path>`,
        so the token never enters /nix/store.
      '';
    };

    labels = mkOption {
      type = types.listOf types.str;
      default = defaultLabels;
      description = ''
        Labels advertised by the runner. Workflows pick runners via
        `runs-on:`. Convention: 'host=<name>', 'size=small|large',
        optionally 'gpu=<model>'.
      '';
    };

    capacity = mkOption {
      type = types.ints.positive;
      default = 1;
      description = "Maximum number of jobs the runner accepts concurrently.";
    };

    jobTimeout = mkOption {
      type = types.str;
      default = "1h";
      example = "1h";
      description = ''
        Hard timeout for any single job. Accepts any Go duration
        string: '30m', '1h', '2h30m', etc.
      '';
    };

    fetchTimeout = mkOption {
      type = types.str;
      default = "30s";
      description = "Timeout for fetching the runner's repository checkout.";
    };

    hostWorkdirParent = mkOption {
      type = types.str;
      default = "/var/lib/forge-runner/work";
      description = ''
        Where job working directories live on the host (not the
        container). Per the v12 schema, this is the `host.workdir_parent`.
      '';
    };

    containerWorkdirParent = mkOption {
      type = types.str;
      default = "/var/lib/forge-runner/container-work";
      description = ''
        Container-side workdir parent. Per the v12 schema, this is
        the `container.workdir_parent`. Must be an absolute path.
      '';
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = ''
        Extra YAML to append to the generated config.yaml verbatim.
        Use for advanced knobs the option set does not cover.
      '';
    };
  };

  config = mkIf cfg.enable {

    # Fail loudly at evaluation time if the token file is missing.
    # We deliberately do NOT read its contents at eval time — that
    # would leak the token into /nix/store.
    assertions = [
      {
        assertion = builtins.pathExists cfg.tokenFile;
        message = ''
          services.forgejo-runner: tokenFile does not exist:
            ${toString cfg.tokenFile}
          The file must contain ONE LINE: the opaque runner token.
          The token is shown once by the Forgejo web UI when you
          create a new runner (Site Administration -> Actions ->
          Runners -> Create new runner).
          Create it with:
            sudo install -m 600 -o forge-runner -g forge-runner \
              /dev/null /etc/nixos/secrets/forgejo-runner-token
            sudo -u forge-runner vi /etc/nixos/secrets/forgejo-runner-token
          Also set services.forgejo-runner.uuid to the UUID shown
          on the same web UI screen.
        '';
      }
    ];

    users.users.forge-runner = {
      isNormalUser = false;
      isSystemUser = true;
      group        = "forge-runner";
      home         = "/var/lib/forge-runner";
      createHome   = true;
      homeMode     = "0750";
      description  = "Forgejo Actions runner daemon account";
      shell        = pkgs.runtimeShell;
      extraGroups  = [ "docker" ];
    };

    users.groups.forge-runner = { };

    systemd.services.forgejo-runner = {
      description = "Forgejo Actions runner daemon";
      wantedBy    = [ "multi-user.target" ];
      after       = [
        "network-online.target"
        "docker.service"
      ];
      wants       = [ "network-online.target" ];
      requires    = [ "docker.service" ];

      # Skip if the token file is missing — typically means a fresh
      # host hasn't had its credentials provisioned yet.
      unitConfig.ConditionPathExists = cfg.tokenFile;

      serviceConfig = {
        Type             = "simple";
        User             = "forge-runner";
        Group            = "forge-runner";
        WorkingDirectory = "/var/lib/forge-runner";
        ExecStart        = "${pkgs.forgejo-runner}/bin/forgejo-runner daemon --config ${configFile}";
        Restart          = "on-failure";
        RestartSec       = "5";
        # Hardening
        NoNewPrivileges         = "true";
        PrivateTmp              = "true";
        ProtectSystem           = "strict";
        ProtectHome             = "true";
        ProtectKernelTunables   = "true";
        ProtectKernelModules    = "true";
        ProtectControlGroups    = "true";
        RestrictAddressFamilies = "AF_INET AF_INET6 AF_NETLINK";
        UMask                   = "0077";
      };
    };
  };

  meta.maintainers = [ "ewt" ];
}
