{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.forgejo-runner;

  # Defaults match what we agreed on in the platform-doc for the Odroid host.
  # Other hosts (um790, vps) override these when they enable the module.
  defaultUrl    = "https://forgejo.tail5bbc4.ts.net";
  defaultLabels = [ "self-hosted" "linux" "x86_64" ];

  configFile = pkgs.writeText "forgejo-runner-config.yaml" (''
    # Generated by modules/forgejo-runner.nix — do not edit by hand.
    # Regenerated on every `nixos-rebuild switch`.

    log:
      level: info

    runner:
      file:           /var/lib/forge-runner/.runner
      capacity:       ${toString cfg.capacity}
      timeout:        ${toString cfg.jobTimeoutSeconds}s
      insecure:       false
      fetch_timeout:  ${toString cfg.fetchTimeoutSeconds}s

    # Cache is disabled for v1. The `cache.host` field expects a string
    # (the cache server hostname), not a map. Setting enabled: true with
    # no host fails the unmarshal. Re-enable when we actually need it.
    cache:
      enabled: false

    container:
      # Rootless Docker is already enabled on the host. The runner
      # spawns one ephemeral container per job as UID `forge` (1000)
      # with --userns=keep-id so bind mounts map back to forge-runner.
      network:     ""
      options:     >-
        --userns=keep-id
      privileged:  false
      force_pull:  false
      runtime:     ""

    host:
      workdir_parent: /var/lib/forge-runner/work

  '' + cfg.extraConfig);

  # forgejo-runner register takes ONE --labels flag whose value is a
  # comma-separated list (matches the server-side `forgejo-cli actions
  # register` and the interactive prompt). Repeating --label fails
  # with `unknown flag: --label`.
  registerArgs = lib.concatStringsSep " " ([
    "${pkgs.forgejo-runner}/bin/forgejo-runner register"
    "--config ${configFile}"
    "--token $(cat ${cfg.tokenFile})"
    "--no-interactive"
    "--name ${escapeShellArg cfg.name}"
    "--labels ${escapeShellArg (lib.concatStringsSep "," cfg.labels)}"
  ]);
in
{
  options.services.forgejo-runner = {
    enable = mkEnableOption "Forgejo Actions runner daemon";

    name = mkOption {
      type = types.str;
      default = "odroid-runner";
      description = ''
        Name shown on the Forgejo Runners page. Defaults to
        'odroid-runner' because the first host enabling this module is
        the Odroid. Override per host.
      '';
    };

    url = mkOption {
      type = types.str;
      default = defaultUrl;
      description = "Forgejo instance URL the runner registers with.";
    };

    tokenFile = mkOption {
      type = types.path;
      default = "/etc/nixos/secrets/forgejo-runner-token";
      description = ''
        Path to a file containing the Forgejo runner registration token.
        The file MUST be mode 600 or 400, owned by root or forge-runner.
        The token itself is sensitive — never commit it to the repo.
        See docs/runners.md for how to obtain the token.
      '';
    };

    labels = mkOption {
      type = types.listOf types.str;
      default = defaultLabels;
      description = ''
        Labels advertised by the runner. Workflows pick runners via
        `runs-on:`. Convention for this platform: 'host=<name>',
        'size=small|large', and optionally 'gpu=<model>'.
      '';
    };

    capacity = mkOption {
      type = types.ints.positive;
      default = 1;
      description = ''
        Maximum number of jobs the runner will accept concurrently.
        The Odroid runs 'size=small' so we cap at 1 by default.
      '';
    };

    jobTimeoutSeconds = mkOption {
      type = types.ints.positive;
      default = 3600;
      description = "Hard timeout for any single job.";
    };

    fetchTimeoutSeconds = mkOption {
      type = types.ints.positive;
      default = 300;
      description = "Timeout for fetching the runner's repository checkout.";
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = ''
        Extra YAML to append to the generated config.yaml verbatim.
        Use for advanced knobs the option set does not cover.
      '';
    };
  };

  config = mkIf cfg.enable {

    # Fail loudly at evaluation time if the token file is missing.
    # Better to break the build than to deploy a runner that can't register.
    assertions = [
      {
        assertion = builtins.pathExists cfg.tokenFile;
        message = ''
          services.forgejo-runner: tokenFile does not exist:
            ${toString cfg.tokenFile}
          Create it with:
            sudo install -m 600 -o forge-runner -g forge-runner \
              /dev/null ${toString cfg.tokenFile}
            sudo -u forge-runner vi ${toString cfg.tokenFile}
          Paste the registration token from the Forgejo web UI
          (Repository -> Settings -> Actions -> Runners -> Create new runner).
        '';
      }
    ];

    users.users.forge-runner = {
      isNormalUser = false;
      isSystemUser = true;
      group        = "forge-runner";
      home         = "/var/lib/forge-runner";
      createHome   = true;
      homeMode     = "0750";
      description  = "Forgejo Actions runner daemon account";
      shell        = pkgs.runtimeShell;  # /bin/sh for systemd only; no interactive login
      # No password. Member of 'docker' so rootless Docker works for spawned job containers.
      extraGroups  = [ "docker" ];
    };

    users.groups.forge-runner = { };

    # One-shot: register the runner with the Forgejo instance.
    # Idempotent: only runs if the .runner file doesn't yet exist.
    systemd.services.forgejo-runner-register = {
      description = "Register Forgejo Actions runner (one-shot)";
      wantedBy    = [ "multi-user.target" ];
      after       = [ "network-online.target" ];
      wants       = [ "network-online.target" ];
      # Idempotent: skip if already registered. This is a [Unit]-level
      # directive in systemd, NOT a [Service] one. Putting it in
      # serviceConfig causes systemd to log
      # 'Unknown key ConditionPathExists in section [Service], ignoring'.
      unitConfig.ConditionPathExists = "!/var/lib/forge-runner/.runner";

      serviceConfig = {
        Type            = "oneshot";
        User            = "forge-runner";
        Group           = "forge-runner";
        RemainAfterExit = "yes";
        ExecStartPre    = "${pkgs.coreutils}/bin/sleep 5";
        # LoadCredential= mounts the token file at
        # $CREDENTIALS_DIRECTORY/token inside the unit. systemd sets
        # $CREDENTIALS_DIRECTORY=/run/credentials/<unitname> automatically.
        # The mounted copy is owned by the unit's User, mode preserved.
        LoadCredential  = "token:${cfg.tokenFile}";
        # Bash wrapper: registerArgs references $(cat ${cfg.tokenFile})
        # which is the path on the host filesystem, but the unit sees the
        # mounted copy at $CREDENTIALS_DIRECTORY/token. We rewrite at
        # Nix-eval time so bash receives the in-unit path as a literal.
        ExecStart = let
          registerForUnit = lib.replaceStrings [cfg.tokenFile] ["\"\$CREDENTIALS_DIRECTORY/token\""] registerArgs;
        in "${pkgs.bash}/bin/bash -c 'exec ${registerForUnit}'";
      };
    };

    # The actual daemon: pulls jobs from the Forgejo queue and runs them.
    systemd.services.forgejo-runner = {
      description = "Forgejo Actions runner daemon";
      wantedBy    = [ "multi-user.target" ];
      after       = [
        "network-online.target"
        "docker.service"
        "forgejo-runner-register.service"
      ];
      wants       = [ "network-online.target" ];
      requires    = [ "docker.service" ];

      serviceConfig = {
        Type             = "simple";
        User             = "forge-runner";
        Group            = "forge-runner";
        WorkingDirectory = "/var/lib/forge-runner";
        ExecStart        = "${pkgs.forgejo-runner}/bin/forgejo-runner daemon --config ${configFile}";
        Restart          = "on-failure";
        RestartSec       = "5";
        # Hardening
        NoNewPrivileges        = "true";
        PrivateTmp             = "true";
        ProtectSystem          = "strict";
        ProtectHome            = "true";
        ProtectKernelTunables  = "true";
        ProtectKernelModules   = "true";
        ProtectControlGroups   = "true";
        RestrictAddressFamilies = "AF_INET AF_INET6 AF_NETLINK";
        UMask                  = "0077";
      };
    };
  };

  meta.maintainers = [ "ewt" ];
}