{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.forgejo-runner;

  defaultUrl    = "https://forgejo.tail5bbc4.ts.net";

  configFile = pkgs.writeText "forgejo-runner-config.yaml" (''
    # Generated by modules/forgejo-runner.nix — do not edit by hand.
    # Regenerated on every `nixos-rebuild switch`.

    log:
      level: info

    runner:
      file:           /var/lib/forge-runner/.runner
      capacity:       ${toString cfg.capacity}
      timeout:        ${toString cfg.jobTimeoutSeconds}s
      insecure:       false
      fetch_timeout:  ${toString cfg.fetchTimeoutSeconds}s

    # Cache is disabled for v1. The `cache.host` field expects a string
    # (the cache server hostname), not a map. Setting enabled: true with
    # no host fails the unmarshal. Re-enable when we actually need it.
    cache:
      enabled: false

    container:
      # Rootless Docker. The runner uses forge-runner's per-user dockerd
      # (set up via the systemd --user instance, see the post-deploy
      # steps in docs/runners.md). The socket lives at
      # /run/user/<UID>/docker.sock. Container workdir_parent defaults
      # to /workspace inside the container.
      network:        ""
      privileged:     false
      force_pull:     false
      runtime:        ""
      workdir_parent: ${cfg.containerWorkdirParent}
      # docker_host empty: the wrapper ExecStart exports DOCKER_HOST at
      # activation time (users.users.<name>.uid is null at eval time, so
      # we cannot bake the socket path into config.yaml).
      # container.options empty: --userns=keep-id is not a valid --userns
      # mode (modes are host|container|private|none). The runner passes
      # -u UID:GID per-job, and rootless docker handles userns at the
      # daemon level.
      options:        ""
    host:
      workdir_parent: ${cfg.hostWorkdirParent}

  '' + cfg.extraConfig);

  # forgejo-runner register takes ONE --labels flag whose value is a
  # comma-separated list (matches the server-side `forgejo-cli actions
  # register` and the interactive prompt). Repeating --label fails
  # with `unknown flag: --label`.
  registerArgs = lib.concatStringsSep " " ([
    "${pkgs.forgejo-runner}/bin/forgejo-runner register"
    "--config ${configFile}"
    "--instance ${escapeShellArg cfg.url}"
    "--token $(cat ${cfg.tokenFile})"
    "--name ${escapeShellArg cfg.name}"
    "--labels ${escapeShellArg (lib.concatStringsSep "," cfg.labels)}"
    "--no-interactive"
  ]);
in
{
  options.services.forgejo-runner = {
    enable = mkEnableOption "Forgejo Actions runner daemon";

    name = mkOption {
      type = types.str;
      # No default: every host picks a name (e.g. "odroid-runner",
      # "um790-runner"). Forcing the host to set it avoids accidental
      # collisions across runners on the same Forgejo instance.
      description = ''
        Name shown on the Forgejo Runners page. Each host should pick
        a unique name (e.g. "odroid-runner").
      '';
    };

    url = mkOption {
      type = types.str;
      default = defaultUrl;
      description = "Forgejo instance URL the runner registers with.";
    };

    tokenFile = mkOption {
      type = types.path;
      default = "/etc/nixos/secrets/forgejo-runner-token";
      description = ''
        Path to a file containing the Forgejo runner registration token.
        The file MUST be mode 600 or 400, owned by root or forge-runner.
        The token itself is sensitive — never commit it to the repo.
        See docs/runners.md for how to obtain the token.
      '';
    };

    labels = mkOption {
      type = types.listOf types.str;
      # No default: every host picks its own labels. At minimum include
      # host=<name> so workflows can target runners by hostname.
      default = [];
      description = ''
        Labels advertised by the runner. Workflows pick runners via
        `runs-on:`. Convention: 'host=<name>', 'size=small|large',
        and optionally 'gpu=<model>'.
      '';
    };

    capacity = mkOption {
      type = types.ints.positive;
      default = 1;
      description = ''
        Maximum number of jobs the runner will accept concurrently.
        The Odroid runs 'size=small' so we cap at 1 by default.
      '';
    };

    jobTimeoutSeconds = mkOption {
      type = types.ints.positive;
      default = 3600;
      description = "Hard timeout for any single job.";
    };

    fetchTimeoutSeconds = mkOption {
      type = types.ints.positive;
      default = 300;
      description = "Timeout for fetching the runner's repository checkout.";
    };
    hostWorkdirParent = mkOption {
      type = types.str;
      default = "/var/lib/forge-runner/work";
      description = ''
        Where job working directories live on the host (not the
        container). Per the v12 schema, this is the `host.workdir_parent`.
      '';
    };

    containerWorkdirParent = mkOption {
      type = types.str;
      default = "/var/lib/forge-runner/container-work";
      description = ''
        Container-side workdir parent. Per the v12 schema, this is
        the `container.workdir_parent`. Must be an absolute path.
      '';
    };

    extraConfig = mkOption {
      default = "";
      description = ''
        Extra YAML to append to the generated config.yaml verbatim.
        Use for advanced knobs the option set does not cover.
      '';
    };
  };

  config = mkIf cfg.enable {

    # Fail loudly at evaluation time if the token file is missing.
    # Better to break the build than to deploy a runner that can't register.
    assertions = [
      {
        assertion = builtins.pathExists cfg.tokenFile;
        message = ''
          services.forgejo-runner: tokenFile does not exist:
            ${toString cfg.tokenFile}
          Create it with:
            sudo install -m 600 -o forge-runner -g forge-runner \
              /dev/null ${toString cfg.tokenFile}
            sudo -u forge-runner vi ${toString cfg.tokenFile}
          Paste the registration token from the Forgejo web UI
          (Repository -> Settings -> Actions -> Runners -> Create new runner).
        '';
      }
    ];

    users.users.forge-runner = {
      isNormalUser = false;
      isSystemUser = true;
      group        = "forge-runner";
      home         = "/var/lib/forge-runner";
      createHome   = true;
      homeMode     = "0750";
      description  = "Forgejo Actions runner daemon account";
      shell        = pkgs.runtimeShell;
      # Rootless Docker setup:
      #   linger = true      → enables user-mode systemd at boot, so the
      #                        rootless dockerd can run as a user service.
      #   subUid/subGidRanges → namespaced UID/GID range for rootless
      #                        Docker. Standard 65k range starting at
      #                        100000. This range is written to /etc/subuid
      #                        and /etc/subgid by NixOS at activation.
      linger       = true;
      subUidRanges = [{ startUid = 100000; count = 65536; }];
      subGidRanges = [{ startGid = 100000; count = 65536; }];
    };

    users.groups.forge-runner = { };

    # One-shot: register the runner with the Forgejo instance.
    # Idempotent: only runs if the .runner file doesn't yet exist.
    systemd.services.forgejo-runner-register = {
      description = "Register Forgejo Actions runner (one-shot)";
      wantedBy    = [ "multi-user.target" ];
      after       = [ "network-online.target" ];
      wants       = [ "network-online.target" ];
      # Idempotent: skip if already registered. This is a [Unit]-level
      # directive in systemd, NOT a [Service] one. Putting it in
      # serviceConfig causes systemd to log
      # 'Unknown key ConditionPathExists in section [Service], ignoring'.
      unitConfig.ConditionPathExists = "!/var/lib/forge-runner/.runner";

      serviceConfig = {
        Type            = "oneshot";
        User            = "forge-runner";
        Group           = "forge-runner";
        RemainAfterExit = "yes";

        # LoadCredential= mounts the token file at
        # $CREDENTIALS_DIRECTORY/token inside the unit. systemd sets
        # $CREDENTIALS_DIRECTORY=/run/credentials/<unitname> automatically.
        # The mounted copy is owned by the unit's User, mode preserved.
        LoadCredential  = "token:${cfg.tokenFile}";
        # Bash wrapper: registerArgs references $(cat ${cfg.tokenFile})
        # which is the path on the host filesystem, but the unit sees the
        # mounted copy at $CREDENTIALS_DIRECTORY/token. We rewrite at
        # Nix-eval time so bash receives the in-unit path as a literal.
        ExecStart = let
          registerForUnit = lib.replaceStrings [cfg.tokenFile] ["\"\$CREDENTIALS_DIRECTORY/token\""] registerArgs;
        in "${pkgs.bash}/bin/bash -c 'exec ${registerForUnit}'";
      };
    };

    # The actual daemon: pulls jobs from the Forgejo queue and runs them.
    systemd.services.forgejo-runner = {
      description = "Forgejo Actions runner daemon";
      wantedBy    = [ "multi-user.target" ];
      # We deliberately do NOT add an `After=user@<UID>.service` here.
      # users.users.forge-runner.uid is null at eval time (NixOS assigns
      # it via useradd at activation), so we cannot compute the unit
      # name. Instead, linger=true ensures user-mode systemd runs the
      # rootless dockerd at boot, and the ExecStartPre wait script
      # discovers the socket with verbose logging.
      serviceConfig = {
        Type             = "simple";
        User             = "forge-runner";
        Group            = "forge-runner";
        WorkingDirectory = "/var/lib/forge-runner";
        # Wrapper script resolves forge-runner's UID at activation time
        # and exports DOCKER_HOST. (UID is null at eval time — see the
        # After= comment above.)
        ExecStart = let
          startScript = pkgs.writeShellScript "forgejo-runner-start" ''
            set -e
            uid=$(id -u forge-runner)
            export DOCKER_HOST="unix:///run/user/$uid/docker.sock"
            exec ${pkgs.forgejo-runner}/bin/forgejo-runner daemon --config ${configFile}
          '';
        in "${startScript}";
        ExecStartPre = let
          # Use Nix-provided store paths for the binaries so the script
          # has no PATH dependency. systemd unit PATH is minimal and
          # NixOS's /usr/bin/seq may not resolve correctly inside the
          # hardened service environment.
          idBin = "${pkgs.coreutils}/bin/id";
          sleepBin = "${pkgs.coreutils}/bin/sleep";
          curlBin = "${pkgs.curl}/bin/curl";
          waitScript = pkgs.writeShellScript "forgejo-runner-wait-docker" ''
            set -eu
            uid=$(${idBin} -u forge-runner)
            socket="/run/user/$uid/docker.sock"
            echo "forgejo-runner wait-docker: uid=$uid socket=$socket"
            for i in $(seq 1 120); do
              if [ -S "$socket" ]; then
                # Socket inode exists. Probe with curl to confirm the
                # dockerd-rootless is actually listening. A stale
                # socket (no listener) makes the runner fail later
                # with a confusing "Cannot connect" error.
                if ${curlBin} --unix-socket "$socket" -sS --max-time 2 \
                     http://localhost/_ping >/dev/null 2>&1; then
                  echo "forgejo-runner wait-docker: dockerd is listening (iter $i)"
                  exit 0
                else
                  echo "forgejo-runner wait-docker: socket present but no listener (iter $i)"
                fi
              else
                echo "forgejo-runner wait-docker: socket not present yet (iter $i)"
              fi
              ${sleepBin} 1
            done
            echo "forgejo-runner wait-docker: gave up after 120s waiting on $socket" >&2
            exit 1
          '';
        in "${waitScript}";
        TimeoutStartSec = "180";
        Restart          = "on-failure";
        RestartSec       = "5";
        # Hardening
        NoNewPrivileges        = "true";
        PrivateTmp             = "true";
        ProtectSystem          = "strict";
        # ProtectHome=true hides /run/user/, which prevents the daemon
        # from seeing its own rootless docker socket at
        # /run/user/<UID>/docker.sock. read-only still hides /home and
        # /root from writes but leaves /run/user/ visible (read-only).
        # The socket is a unix-domain socket — we connect to it; we
        # never need to write into /run/user/.
        ProtectHome            = "read-only";
        ProtectKernelTunables  = "true";
        ProtectKernelModules   = "true";
        ProtectControlGroups   = "true";
        # AF_UNIX is needed to reach the docker socket. The runner
        # only talks to forge-runner's rootless socket at
        # /run/user/<UID>/docker.sock — no other AF_UNIX endpoints.
        RestrictAddressFamilies = "AF_UNIX AF_INET AF_INET6 AF_NETLINK";
        UMask                  = "0077";
      };
    };
  };

  meta.maintainers = [ "ewt" ];
}